PREFIX onto: <http://krr.org/space_exploration.owl#>
PREFIX ex: <http://krr.org/space/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?mission ?missionName ?launchDate
WHERE {
    ?mission rdf:type onto:MoonMission .
    ?mission onto:missionName ?missionName .
    ?mission onto:launchDate ?launchDate .
}
ORDER BY ?launchDate

