PREFIX onto: <http://krr.org/space_exploration.owl#>
PREFIX ex: <http://krr.org/space/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?mission ?missionName
WHERE {
    ?mission rdf:type onto:SpaceMission .
    ?mission onto:missionName ?missionName .
}
ORDER BY ?missionName

