PREFIX onto: <http://krr.org/space_exploration.owl#>
PREFIX ex: <http://krr.org/space/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?agency ?country
WHERE {
    ?agency rdf:type onto:Agency .
    ?agency onto:refersToCountry ?country .
}

