PREFIX onto: <http://krr.org/space_exploration.owl#>
PREFIX ex: <http://krr.org/space/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?mission ?missionName ?launchDate
WHERE {
    ?mission rdf:type onto:SpaceMission .
    ?mission onto:missionName ?missionName .
    ?mission onto:launchDate ?launchDate .
    FILTER (regex(?launchDate, "2023", "i"))
}
ORDER BY ?launchDate

