PREFIX onto: <http://krr.org/space_exploration.owl#>
PREFIX ex: <http://krr.org/space/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?mission ?missionName ?budget
WHERE {
    ?mission rdf:type onto:SpaceMission .
    ?mission onto:missionName ?missionName .
    ?mission onto:hasBudget ?budget .
    FILTER (regex(?missionName, "Apollo 11", "i"))
}

