PREFIX onto: <http://krr.org/space_exploration.owl#>
PREFIX ex: <http://krr.org/space/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# Query for CommercialSpaceFlight (defined class: intersection of SpaceMission and launchedBy PrivateCompany)
SELECT ?mission ?missionName ?company
WHERE {
    ?mission rdf:type onto:CommercialSpaceFlight .
    ?mission onto:missionName ?missionName .
    ?mission onto:launchedBy ?company .
}

